### ISSUE TITLE
CLA.json boolean property for if a contributor has contributed

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium-concierge#93] opened 2018-01-15 14:37 UTC
Some contributors submit a CLA but never contribute.  Before the concierge, we use to track this.

This would also be useful so that we would start listing all contributors in the Schedule A of a corporate CLA also as individual contributors who have not contributed so that they are not incorrectly flagged as not having a CLA when they open their first PR.  Alternatively, the Schedule A could be more precisely defined in CLA.json so that it can be checked for these cases.

CC #85

**Comment by OmarShehata** [comment] 2018-06-28 14:09
This is a duplicate of https://github.com/AnalyticalGraphicsInc/cesium-concierge/issues/82

**Closed** 2018-06-28 15:01 UTC
